DROP SCHEMA IF EXISTS aula12;
CREATE SCHEMA aula12;
USE aula12;

CREATE TABLE usuario (
    id INT PRIMARY KEY,
    nome VARCHAR(45) NOT NULL,
    email VARCHAR(255) NOT NULL,
    fone VARCHAR(20)
)ENGINE=InnoDB;

CREATE TABLE forum (
    id INT PRIMARY KEY,
    titulo VARCHAR(45) NOT NULL,
    data_criacao DATE
)ENGINE=InnoDB;

